package cn.edu.guet.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlanDesignConsistencyResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignConsistencyResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNull() {
            addCriterion("plan_design_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNotNull() {
            addCriterion("plan_design_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdEqualTo(Long value) {
            addCriterion("plan_design_id =", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotEqualTo(Long value) {
            addCriterion("plan_design_id <>", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThan(Long value) {
            addCriterion("plan_design_id >", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_design_id >=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThan(Long value) {
            addCriterion("plan_design_id <", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_design_id <=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIn(List<Long> values) {
            addCriterion("plan_design_id in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotIn(List<Long> values) {
            addCriterion("plan_design_id not in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdBetween(Long value1, Long value2) {
            addCriterion("plan_design_id between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_design_id not between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIsNull() {
            addCriterion("plan_design_result_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIsNotNull() {
            addCriterion("plan_design_result_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdEqualTo(Long value) {
            addCriterion("plan_design_result_id =", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotEqualTo(Long value) {
            addCriterion("plan_design_result_id <>", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdGreaterThan(Long value) {
            addCriterion("plan_design_result_id >", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_design_result_id >=", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdLessThan(Long value) {
            addCriterion("plan_design_result_id <", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_design_result_id <=", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIn(List<Long> values) {
            addCriterion("plan_design_result_id in", values, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotIn(List<Long> values) {
            addCriterion("plan_design_result_id not in", values, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdBetween(Long value1, Long value2) {
            addCriterion("plan_design_result_id between", value1, value2, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_design_result_id not between", value1, value2, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumIsNull() {
            addCriterion("analys_cad_num is null");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumIsNotNull() {
            addCriterion("analys_cad_num is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumEqualTo(Integer value) {
            addCriterion("analys_cad_num =", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumNotEqualTo(Integer value) {
            addCriterion("analys_cad_num <>", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumGreaterThan(Integer value) {
            addCriterion("analys_cad_num >", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("analys_cad_num >=", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumLessThan(Integer value) {
            addCriterion("analys_cad_num <", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumLessThanOrEqualTo(Integer value) {
            addCriterion("analys_cad_num <=", value, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumIn(List<Integer> values) {
            addCriterion("analys_cad_num in", values, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumNotIn(List<Integer> values) {
            addCriterion("analys_cad_num not in", values, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumBetween(Integer value1, Integer value2) {
            addCriterion("analys_cad_num between", value1, value2, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysCadNumNotBetween(Integer value1, Integer value2) {
            addCriterion("analys_cad_num not between", value1, value2, "analysCadNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumIsNull() {
            addCriterion("analys_excel_num is null");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumIsNotNull() {
            addCriterion("analys_excel_num is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumEqualTo(Integer value) {
            addCriterion("analys_excel_num =", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumNotEqualTo(Integer value) {
            addCriterion("analys_excel_num <>", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumGreaterThan(Integer value) {
            addCriterion("analys_excel_num >", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("analys_excel_num >=", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumLessThan(Integer value) {
            addCriterion("analys_excel_num <", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumLessThanOrEqualTo(Integer value) {
            addCriterion("analys_excel_num <=", value, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumIn(List<Integer> values) {
            addCriterion("analys_excel_num in", values, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumNotIn(List<Integer> values) {
            addCriterion("analys_excel_num not in", values, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumBetween(Integer value1, Integer value2) {
            addCriterion("analys_excel_num between", value1, value2, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysExcelNumNotBetween(Integer value1, Integer value2) {
            addCriterion("analys_excel_num not between", value1, value2, "analysExcelNum");
            return (Criteria) this;
        }

        public Criteria andAnalysResultIsNull() {
            addCriterion("analys_result is null");
            return (Criteria) this;
        }

        public Criteria andAnalysResultIsNotNull() {
            addCriterion("analys_result is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysResultEqualTo(String value) {
            addCriterion("analys_result =", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultNotEqualTo(String value) {
            addCriterion("analys_result <>", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultGreaterThan(String value) {
            addCriterion("analys_result >", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultGreaterThanOrEqualTo(String value) {
            addCriterion("analys_result >=", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultLessThan(String value) {
            addCriterion("analys_result <", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultLessThanOrEqualTo(String value) {
            addCriterion("analys_result <=", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultLike(String value) {
            addCriterion("analys_result like", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultNotLike(String value) {
            addCriterion("analys_result not like", value, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultIn(List<String> values) {
            addCriterion("analys_result in", values, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultNotIn(List<String> values) {
            addCriterion("analys_result not in", values, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultBetween(String value1, String value2) {
            addCriterion("analys_result between", value1, value2, "analysResult");
            return (Criteria) this;
        }

        public Criteria andAnalysResultNotBetween(String value1, String value2) {
            addCriterion("analys_result not between", value1, value2, "analysResult");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 20 21:02:33 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_consistency_result
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}