package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class PlanDesignHistoryRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.Id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.plan_design_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Long planDesignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_no
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String analyseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_status
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Byte analyseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_begin_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Date analyseBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_end_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Date analyseEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Integer analyseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Integer systemCadFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String systemCadFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String systemCadFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Integer systemExcelFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String systemExcelFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String systemExcelFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Integer channelExcelFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String channelExcelFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String channelExcelFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_log
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String analyseLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_staff_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Long analyseStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.analyse_staff_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private String analyseStaffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_history_record.create_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.Id
     *
     * @return the value of t_plan_design_history_record.Id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.Id
     *
     * @param id the value for t_plan_design_history_record.Id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.plan_design_id
     *
     * @return the value of t_plan_design_history_record.plan_design_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Long getPlanDesignId() {
        return planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withPlanDesignId(Long planDesignId) {
        this.setPlanDesignId(planDesignId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.plan_design_id
     *
     * @param planDesignId the value for t_plan_design_history_record.plan_design_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setPlanDesignId(Long planDesignId) {
        this.planDesignId = planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_no
     *
     * @return the value of t_plan_design_history_record.analyse_no
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getAnalyseNo() {
        return analyseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseNo(String analyseNo) {
        this.setAnalyseNo(analyseNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_no
     *
     * @param analyseNo the value for t_plan_design_history_record.analyse_no
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseNo(String analyseNo) {
        this.analyseNo = analyseNo == null ? null : analyseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_status
     *
     * @return the value of t_plan_design_history_record.analyse_status
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Byte getAnalyseStatus() {
        return analyseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseStatus(Byte analyseStatus) {
        this.setAnalyseStatus(analyseStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_status
     *
     * @param analyseStatus the value for t_plan_design_history_record.analyse_status
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseStatus(Byte analyseStatus) {
        this.analyseStatus = analyseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_begin_time
     *
     * @return the value of t_plan_design_history_record.analyse_begin_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Date getAnalyseBeginTime() {
        return analyseBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseBeginTime(Date analyseBeginTime) {
        this.setAnalyseBeginTime(analyseBeginTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_begin_time
     *
     * @param analyseBeginTime the value for t_plan_design_history_record.analyse_begin_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseBeginTime(Date analyseBeginTime) {
        this.analyseBeginTime = analyseBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_end_time
     *
     * @return the value of t_plan_design_history_record.analyse_end_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Date getAnalyseEndTime() {
        return analyseEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseEndTime(Date analyseEndTime) {
        this.setAnalyseEndTime(analyseEndTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_end_time
     *
     * @param analyseEndTime the value for t_plan_design_history_record.analyse_end_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseEndTime(Date analyseEndTime) {
        this.analyseEndTime = analyseEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_time
     *
     * @return the value of t_plan_design_history_record.analyse_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Integer getAnalyseTime() {
        return analyseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseTime(Integer analyseTime) {
        this.setAnalyseTime(analyseTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_time
     *
     * @param analyseTime the value for t_plan_design_history_record.analyse_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseTime(Integer analyseTime) {
        this.analyseTime = analyseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_cad_file_id
     *
     * @return the value of t_plan_design_history_record.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Integer getSystemCadFileId() {
        return systemCadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemCadFileId(Integer systemCadFileId) {
        this.setSystemCadFileId(systemCadFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_cad_file_id
     *
     * @param systemCadFileId the value for t_plan_design_history_record.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemCadFileId(Integer systemCadFileId) {
        this.systemCadFileId = systemCadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_cad_file_name
     *
     * @return the value of t_plan_design_history_record.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getSystemCadFileName() {
        return systemCadFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemCadFileName(String systemCadFileName) {
        this.setSystemCadFileName(systemCadFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_cad_file_name
     *
     * @param systemCadFileName the value for t_plan_design_history_record.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemCadFileName(String systemCadFileName) {
        this.systemCadFileName = systemCadFileName == null ? null : systemCadFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_cad_file_url
     *
     * @return the value of t_plan_design_history_record.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getSystemCadFileUrl() {
        return systemCadFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemCadFileUrl(String systemCadFileUrl) {
        this.setSystemCadFileUrl(systemCadFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_cad_file_url
     *
     * @param systemCadFileUrl the value for t_plan_design_history_record.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemCadFileUrl(String systemCadFileUrl) {
        this.systemCadFileUrl = systemCadFileUrl == null ? null : systemCadFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_excel_file_id
     *
     * @return the value of t_plan_design_history_record.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Integer getSystemExcelFileId() {
        return systemExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemExcelFileId(Integer systemExcelFileId) {
        this.setSystemExcelFileId(systemExcelFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_excel_file_id
     *
     * @param systemExcelFileId the value for t_plan_design_history_record.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemExcelFileId(Integer systemExcelFileId) {
        this.systemExcelFileId = systemExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_excel_file_name
     *
     * @return the value of t_plan_design_history_record.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getSystemExcelFileName() {
        return systemExcelFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemExcelFileName(String systemExcelFileName) {
        this.setSystemExcelFileName(systemExcelFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_excel_file_name
     *
     * @param systemExcelFileName the value for t_plan_design_history_record.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemExcelFileName(String systemExcelFileName) {
        this.systemExcelFileName = systemExcelFileName == null ? null : systemExcelFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.system_excel_file_url
     *
     * @return the value of t_plan_design_history_record.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getSystemExcelFileUrl() {
        return systemExcelFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withSystemExcelFileUrl(String systemExcelFileUrl) {
        this.setSystemExcelFileUrl(systemExcelFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.system_excel_file_url
     *
     * @param systemExcelFileUrl the value for t_plan_design_history_record.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setSystemExcelFileUrl(String systemExcelFileUrl) {
        this.systemExcelFileUrl = systemExcelFileUrl == null ? null : systemExcelFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.channel_excel_file_id
     *
     * @return the value of t_plan_design_history_record.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Integer getChannelExcelFileId() {
        return channelExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withChannelExcelFileId(Integer channelExcelFileId) {
        this.setChannelExcelFileId(channelExcelFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.channel_excel_file_id
     *
     * @param channelExcelFileId the value for t_plan_design_history_record.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setChannelExcelFileId(Integer channelExcelFileId) {
        this.channelExcelFileId = channelExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.channel_excel_file_name
     *
     * @return the value of t_plan_design_history_record.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getChannelExcelFileName() {
        return channelExcelFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withChannelExcelFileName(String channelExcelFileName) {
        this.setChannelExcelFileName(channelExcelFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.channel_excel_file_name
     *
     * @param channelExcelFileName the value for t_plan_design_history_record.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setChannelExcelFileName(String channelExcelFileName) {
        this.channelExcelFileName = channelExcelFileName == null ? null : channelExcelFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.channel_excel_file_url
     *
     * @return the value of t_plan_design_history_record.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getChannelExcelFileUrl() {
        return channelExcelFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withChannelExcelFileUrl(String channelExcelFileUrl) {
        this.setChannelExcelFileUrl(channelExcelFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.channel_excel_file_url
     *
     * @param channelExcelFileUrl the value for t_plan_design_history_record.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setChannelExcelFileUrl(String channelExcelFileUrl) {
        this.channelExcelFileUrl = channelExcelFileUrl == null ? null : channelExcelFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_log
     *
     * @return the value of t_plan_design_history_record.analyse_log
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getAnalyseLog() {
        return analyseLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseLog(String analyseLog) {
        this.setAnalyseLog(analyseLog);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_log
     *
     * @param analyseLog the value for t_plan_design_history_record.analyse_log
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseLog(String analyseLog) {
        this.analyseLog = analyseLog == null ? null : analyseLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_staff_id
     *
     * @return the value of t_plan_design_history_record.analyse_staff_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Long getAnalyseStaffId() {
        return analyseStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseStaffId(Long analyseStaffId) {
        this.setAnalyseStaffId(analyseStaffId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_staff_id
     *
     * @param analyseStaffId the value for t_plan_design_history_record.analyse_staff_id
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseStaffId(Long analyseStaffId) {
        this.analyseStaffId = analyseStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.analyse_staff_name
     *
     * @return the value of t_plan_design_history_record.analyse_staff_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getAnalyseStaffName() {
        return analyseStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withAnalyseStaffName(String analyseStaffName) {
        this.setAnalyseStaffName(analyseStaffName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.analyse_staff_name
     *
     * @param analyseStaffName the value for t_plan_design_history_record.analyse_staff_name
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setAnalyseStaffName(String analyseStaffName) {
        this.analyseStaffName = analyseStaffName == null ? null : analyseStaffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_history_record.create_time
     *
     * @return the value of t_plan_design_history_record.create_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecord withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_history_record.create_time
     *
     * @param createTime the value for t_plan_design_history_record.create_time
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", planDesignId=").append(planDesignId);
        sb.append(", analyseNo=").append(analyseNo);
        sb.append(", analyseStatus=").append(analyseStatus);
        sb.append(", analyseBeginTime=").append(analyseBeginTime);
        sb.append(", analyseEndTime=").append(analyseEndTime);
        sb.append(", analyseTime=").append(analyseTime);
        sb.append(", systemCadFileId=").append(systemCadFileId);
        sb.append(", systemCadFileName=").append(systemCadFileName);
        sb.append(", systemCadFileUrl=").append(systemCadFileUrl);
        sb.append(", systemExcelFileId=").append(systemExcelFileId);
        sb.append(", systemExcelFileName=").append(systemExcelFileName);
        sb.append(", systemExcelFileUrl=").append(systemExcelFileUrl);
        sb.append(", channelExcelFileId=").append(channelExcelFileId);
        sb.append(", channelExcelFileName=").append(channelExcelFileName);
        sb.append(", channelExcelFileUrl=").append(channelExcelFileUrl);
        sb.append(", analyseLog=").append(analyseLog);
        sb.append(", analyseStaffId=").append(analyseStaffId);
        sb.append(", analyseStaffName=").append(analyseStaffName);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}