package cn.edu.guet.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlanDesignBusinessRouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRouteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNull() {
            addCriterion("plan_design_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNotNull() {
            addCriterion("plan_design_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdEqualTo(Long value) {
            addCriterion("plan_design_id =", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotEqualTo(Long value) {
            addCriterion("plan_design_id <>", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThan(Long value) {
            addCriterion("plan_design_id >", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_design_id >=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThan(Long value) {
            addCriterion("plan_design_id <", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_design_id <=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIn(List<Long> values) {
            addCriterion("plan_design_id in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotIn(List<Long> values) {
            addCriterion("plan_design_id not in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdBetween(Long value1, Long value2) {
            addCriterion("plan_design_id between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_design_id not between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIsNull() {
            addCriterion("plan_design_result_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIsNotNull() {
            addCriterion("plan_design_result_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdEqualTo(Long value) {
            addCriterion("plan_design_result_id =", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotEqualTo(Long value) {
            addCriterion("plan_design_result_id <>", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdGreaterThan(Long value) {
            addCriterion("plan_design_result_id >", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_design_result_id >=", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdLessThan(Long value) {
            addCriterion("plan_design_result_id <", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_design_result_id <=", value, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdIn(List<Long> values) {
            addCriterion("plan_design_result_id in", values, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotIn(List<Long> values) {
            addCriterion("plan_design_result_id not in", values, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdBetween(Long value1, Long value2) {
            addCriterion("plan_design_result_id between", value1, value2, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignResultIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_design_result_id not between", value1, value2, "planDesignResultId");
            return (Criteria) this;
        }

        public Criteria andCircleNameIsNull() {
            addCriterion("circle_name is null");
            return (Criteria) this;
        }

        public Criteria andCircleNameIsNotNull() {
            addCriterion("circle_name is not null");
            return (Criteria) this;
        }

        public Criteria andCircleNameEqualTo(String value) {
            addCriterion("circle_name =", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameNotEqualTo(String value) {
            addCriterion("circle_name <>", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameGreaterThan(String value) {
            addCriterion("circle_name >", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameGreaterThanOrEqualTo(String value) {
            addCriterion("circle_name >=", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameLessThan(String value) {
            addCriterion("circle_name <", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameLessThanOrEqualTo(String value) {
            addCriterion("circle_name <=", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameLike(String value) {
            addCriterion("circle_name like", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameNotLike(String value) {
            addCriterion("circle_name not like", value, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameIn(List<String> values) {
            addCriterion("circle_name in", values, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameNotIn(List<String> values) {
            addCriterion("circle_name not in", values, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameBetween(String value1, String value2) {
            addCriterion("circle_name between", value1, value2, "circleName");
            return (Criteria) this;
        }

        public Criteria andCircleNameNotBetween(String value1, String value2) {
            addCriterion("circle_name not between", value1, value2, "circleName");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("business_type is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("business_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("business_type =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("business_type <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("business_type >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("business_type >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("business_type <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("business_type <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("business_type like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("business_type not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("business_type in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("business_type not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("business_type between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("business_type not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelIsNull() {
            addCriterion("business_channel is null");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelIsNotNull() {
            addCriterion("business_channel is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelEqualTo(String value) {
            addCriterion("business_channel =", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelNotEqualTo(String value) {
            addCriterion("business_channel <>", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelGreaterThan(String value) {
            addCriterion("business_channel >", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelGreaterThanOrEqualTo(String value) {
            addCriterion("business_channel >=", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelLessThan(String value) {
            addCriterion("business_channel <", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelLessThanOrEqualTo(String value) {
            addCriterion("business_channel <=", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelLike(String value) {
            addCriterion("business_channel like", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelNotLike(String value) {
            addCriterion("business_channel not like", value, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelIn(List<String> values) {
            addCriterion("business_channel in", values, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelNotIn(List<String> values) {
            addCriterion("business_channel not in", values, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelBetween(String value1, String value2) {
            addCriterion("business_channel between", value1, value2, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andBusinessChannelNotBetween(String value1, String value2) {
            addCriterion("business_channel not between", value1, value2, "businessChannel");
            return (Criteria) this;
        }

        public Criteria andStationAIsNull() {
            addCriterion("station_a is null");
            return (Criteria) this;
        }

        public Criteria andStationAIsNotNull() {
            addCriterion("station_a is not null");
            return (Criteria) this;
        }

        public Criteria andStationAEqualTo(String value) {
            addCriterion("station_a =", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationANotEqualTo(String value) {
            addCriterion("station_a <>", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationAGreaterThan(String value) {
            addCriterion("station_a >", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationAGreaterThanOrEqualTo(String value) {
            addCriterion("station_a >=", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationALessThan(String value) {
            addCriterion("station_a <", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationALessThanOrEqualTo(String value) {
            addCriterion("station_a <=", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationALike(String value) {
            addCriterion("station_a like", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationANotLike(String value) {
            addCriterion("station_a not like", value, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationAIn(List<String> values) {
            addCriterion("station_a in", values, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationANotIn(List<String> values) {
            addCriterion("station_a not in", values, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationABetween(String value1, String value2) {
            addCriterion("station_a between", value1, value2, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationANotBetween(String value1, String value2) {
            addCriterion("station_a not between", value1, value2, "stationA");
            return (Criteria) this;
        }

        public Criteria andStationZIsNull() {
            addCriterion("station_z is null");
            return (Criteria) this;
        }

        public Criteria andStationZIsNotNull() {
            addCriterion("station_z is not null");
            return (Criteria) this;
        }

        public Criteria andStationZEqualTo(String value) {
            addCriterion("station_z =", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZNotEqualTo(String value) {
            addCriterion("station_z <>", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZGreaterThan(String value) {
            addCriterion("station_z >", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZGreaterThanOrEqualTo(String value) {
            addCriterion("station_z >=", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZLessThan(String value) {
            addCriterion("station_z <", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZLessThanOrEqualTo(String value) {
            addCriterion("station_z <=", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZLike(String value) {
            addCriterion("station_z like", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZNotLike(String value) {
            addCriterion("station_z not like", value, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZIn(List<String> values) {
            addCriterion("station_z in", values, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZNotIn(List<String> values) {
            addCriterion("station_z not in", values, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZBetween(String value1, String value2) {
            addCriterion("station_z between", value1, value2, "stationZ");
            return (Criteria) this;
        }

        public Criteria andStationZNotBetween(String value1, String value2) {
            addCriterion("station_z not between", value1, value2, "stationZ");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterIsNull() {
            addCriterion("business_character is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterIsNotNull() {
            addCriterion("business_character is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterEqualTo(String value) {
            addCriterion("business_character =", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterNotEqualTo(String value) {
            addCriterion("business_character <>", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterGreaterThan(String value) {
            addCriterion("business_character >", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterGreaterThanOrEqualTo(String value) {
            addCriterion("business_character >=", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterLessThan(String value) {
            addCriterion("business_character <", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterLessThanOrEqualTo(String value) {
            addCriterion("business_character <=", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterLike(String value) {
            addCriterion("business_character like", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterNotLike(String value) {
            addCriterion("business_character not like", value, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterIn(List<String> values) {
            addCriterion("business_character in", values, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterNotIn(List<String> values) {
            addCriterion("business_character not in", values, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterBetween(String value1, String value2) {
            addCriterion("business_character between", value1, value2, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andBusinessCharacterNotBetween(String value1, String value2) {
            addCriterion("business_character not between", value1, value2, "businessCharacter");
            return (Criteria) this;
        }

        public Criteria andMainRouteIsNull() {
            addCriterion("main_route is null");
            return (Criteria) this;
        }

        public Criteria andMainRouteIsNotNull() {
            addCriterion("main_route is not null");
            return (Criteria) this;
        }

        public Criteria andMainRouteEqualTo(String value) {
            addCriterion("main_route =", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteNotEqualTo(String value) {
            addCriterion("main_route <>", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteGreaterThan(String value) {
            addCriterion("main_route >", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteGreaterThanOrEqualTo(String value) {
            addCriterion("main_route >=", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteLessThan(String value) {
            addCriterion("main_route <", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteLessThanOrEqualTo(String value) {
            addCriterion("main_route <=", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteLike(String value) {
            addCriterion("main_route like", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteNotLike(String value) {
            addCriterion("main_route not like", value, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteIn(List<String> values) {
            addCriterion("main_route in", values, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteNotIn(List<String> values) {
            addCriterion("main_route not in", values, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteBetween(String value1, String value2) {
            addCriterion("main_route between", value1, value2, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andMainRouteNotBetween(String value1, String value2) {
            addCriterion("main_route not between", value1, value2, "mainRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteIsNull() {
            addCriterion("backup_route is null");
            return (Criteria) this;
        }

        public Criteria andBackupRouteIsNotNull() {
            addCriterion("backup_route is not null");
            return (Criteria) this;
        }

        public Criteria andBackupRouteEqualTo(String value) {
            addCriterion("backup_route =", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteNotEqualTo(String value) {
            addCriterion("backup_route <>", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteGreaterThan(String value) {
            addCriterion("backup_route >", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteGreaterThanOrEqualTo(String value) {
            addCriterion("backup_route >=", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteLessThan(String value) {
            addCriterion("backup_route <", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteLessThanOrEqualTo(String value) {
            addCriterion("backup_route <=", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteLike(String value) {
            addCriterion("backup_route like", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteNotLike(String value) {
            addCriterion("backup_route not like", value, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteIn(List<String> values) {
            addCriterion("backup_route in", values, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteNotIn(List<String> values) {
            addCriterion("backup_route not in", values, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteBetween(String value1, String value2) {
            addCriterion("backup_route between", value1, value2, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andBackupRouteNotBetween(String value1, String value2) {
            addCriterion("backup_route not between", value1, value2, "backupRoute");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailIsNull() {
            addCriterion("same_route_detail is null");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailIsNotNull() {
            addCriterion("same_route_detail is not null");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailEqualTo(String value) {
            addCriterion("same_route_detail =", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailNotEqualTo(String value) {
            addCriterion("same_route_detail <>", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailGreaterThan(String value) {
            addCriterion("same_route_detail >", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailGreaterThanOrEqualTo(String value) {
            addCriterion("same_route_detail >=", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailLessThan(String value) {
            addCriterion("same_route_detail <", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailLessThanOrEqualTo(String value) {
            addCriterion("same_route_detail <=", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailLike(String value) {
            addCriterion("same_route_detail like", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailNotLike(String value) {
            addCriterion("same_route_detail not like", value, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailIn(List<String> values) {
            addCriterion("same_route_detail in", values, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailNotIn(List<String> values) {
            addCriterion("same_route_detail not in", values, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailBetween(String value1, String value2) {
            addCriterion("same_route_detail between", value1, value2, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameRouteDetailNotBetween(String value1, String value2) {
            addCriterion("same_route_detail not between", value1, value2, "sameRouteDetail");
            return (Criteria) this;
        }

        public Criteria andSameStationNameIsNull() {
            addCriterion("same_station_name is null");
            return (Criteria) this;
        }

        public Criteria andSameStationNameIsNotNull() {
            addCriterion("same_station_name is not null");
            return (Criteria) this;
        }

        public Criteria andSameStationNameEqualTo(String value) {
            addCriterion("same_station_name =", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameNotEqualTo(String value) {
            addCriterion("same_station_name <>", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameGreaterThan(String value) {
            addCriterion("same_station_name >", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("same_station_name >=", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameLessThan(String value) {
            addCriterion("same_station_name <", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameLessThanOrEqualTo(String value) {
            addCriterion("same_station_name <=", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameLike(String value) {
            addCriterion("same_station_name like", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameNotLike(String value) {
            addCriterion("same_station_name not like", value, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameIn(List<String> values) {
            addCriterion("same_station_name in", values, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameNotIn(List<String> values) {
            addCriterion("same_station_name not in", values, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameBetween(String value1, String value2) {
            addCriterion("same_station_name between", value1, value2, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andSameStationNameNotBetween(String value1, String value2) {
            addCriterion("same_station_name not between", value1, value2, "sameStationName");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteIsNull() {
            addCriterion("is_same_route is null");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteIsNotNull() {
            addCriterion("is_same_route is not null");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteEqualTo(Byte value) {
            addCriterion("is_same_route =", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteNotEqualTo(Byte value) {
            addCriterion("is_same_route <>", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteGreaterThan(Byte value) {
            addCriterion("is_same_route >", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_same_route >=", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteLessThan(Byte value) {
            addCriterion("is_same_route <", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteLessThanOrEqualTo(Byte value) {
            addCriterion("is_same_route <=", value, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteIn(List<Byte> values) {
            addCriterion("is_same_route in", values, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteNotIn(List<Byte> values) {
            addCriterion("is_same_route not in", values, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteBetween(Byte value1, Byte value2) {
            addCriterion("is_same_route between", value1, value2, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andIsSameRouteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_same_route not between", value1, value2, "isSameRoute");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 20 20:11:55 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}