package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class PlanDesignBusinessRoute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.Id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.plan_design_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private Long planDesignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private Long planDesignResultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.circle_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String circleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.business_type
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.business_channel
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String businessChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.station_a
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String stationA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.station_z
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String stationZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.business_character
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String businessCharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.main_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String mainRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.backup_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String backupRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.same_route_detail
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String sameRouteDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.same_station_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private String sameStationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.is_same_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private Byte isSameRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_business_route.create_time
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.Id
     *
     * @return the value of t_plan_design_business_route.Id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.Id
     *
     * @param id the value for t_plan_design_business_route.Id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.plan_design_id
     *
     * @return the value of t_plan_design_business_route.plan_design_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Long getPlanDesignId() {
        return planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withPlanDesignId(Long planDesignId) {
        this.setPlanDesignId(planDesignId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.plan_design_id
     *
     * @param planDesignId the value for t_plan_design_business_route.plan_design_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setPlanDesignId(Long planDesignId) {
        this.planDesignId = planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.plan_design_result_id
     *
     * @return the value of t_plan_design_business_route.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Long getPlanDesignResultId() {
        return planDesignResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withPlanDesignResultId(Long planDesignResultId) {
        this.setPlanDesignResultId(planDesignResultId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.plan_design_result_id
     *
     * @param planDesignResultId the value for t_plan_design_business_route.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setPlanDesignResultId(Long planDesignResultId) {
        this.planDesignResultId = planDesignResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.circle_name
     *
     * @return the value of t_plan_design_business_route.circle_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getCircleName() {
        return circleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withCircleName(String circleName) {
        this.setCircleName(circleName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.circle_name
     *
     * @param circleName the value for t_plan_design_business_route.circle_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setCircleName(String circleName) {
        this.circleName = circleName == null ? null : circleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.business_type
     *
     * @return the value of t_plan_design_business_route.business_type
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withBusinessType(String businessType) {
        this.setBusinessType(businessType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.business_type
     *
     * @param businessType the value for t_plan_design_business_route.business_type
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.business_channel
     *
     * @return the value of t_plan_design_business_route.business_channel
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getBusinessChannel() {
        return businessChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withBusinessChannel(String businessChannel) {
        this.setBusinessChannel(businessChannel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.business_channel
     *
     * @param businessChannel the value for t_plan_design_business_route.business_channel
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setBusinessChannel(String businessChannel) {
        this.businessChannel = businessChannel == null ? null : businessChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.station_a
     *
     * @return the value of t_plan_design_business_route.station_a
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getStationA() {
        return stationA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withStationA(String stationA) {
        this.setStationA(stationA);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.station_a
     *
     * @param stationA the value for t_plan_design_business_route.station_a
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setStationA(String stationA) {
        this.stationA = stationA == null ? null : stationA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.station_z
     *
     * @return the value of t_plan_design_business_route.station_z
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getStationZ() {
        return stationZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withStationZ(String stationZ) {
        this.setStationZ(stationZ);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.station_z
     *
     * @param stationZ the value for t_plan_design_business_route.station_z
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setStationZ(String stationZ) {
        this.stationZ = stationZ == null ? null : stationZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.business_character
     *
     * @return the value of t_plan_design_business_route.business_character
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getBusinessCharacter() {
        return businessCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withBusinessCharacter(String businessCharacter) {
        this.setBusinessCharacter(businessCharacter);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.business_character
     *
     * @param businessCharacter the value for t_plan_design_business_route.business_character
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setBusinessCharacter(String businessCharacter) {
        this.businessCharacter = businessCharacter == null ? null : businessCharacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.main_route
     *
     * @return the value of t_plan_design_business_route.main_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getMainRoute() {
        return mainRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withMainRoute(String mainRoute) {
        this.setMainRoute(mainRoute);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.main_route
     *
     * @param mainRoute the value for t_plan_design_business_route.main_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setMainRoute(String mainRoute) {
        this.mainRoute = mainRoute == null ? null : mainRoute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.backup_route
     *
     * @return the value of t_plan_design_business_route.backup_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getBackupRoute() {
        return backupRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withBackupRoute(String backupRoute) {
        this.setBackupRoute(backupRoute);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.backup_route
     *
     * @param backupRoute the value for t_plan_design_business_route.backup_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setBackupRoute(String backupRoute) {
        this.backupRoute = backupRoute == null ? null : backupRoute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.same_route_detail
     *
     * @return the value of t_plan_design_business_route.same_route_detail
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getSameRouteDetail() {
        return sameRouteDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withSameRouteDetail(String sameRouteDetail) {
        this.setSameRouteDetail(sameRouteDetail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.same_route_detail
     *
     * @param sameRouteDetail the value for t_plan_design_business_route.same_route_detail
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setSameRouteDetail(String sameRouteDetail) {
        this.sameRouteDetail = sameRouteDetail == null ? null : sameRouteDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.same_station_name
     *
     * @return the value of t_plan_design_business_route.same_station_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public String getSameStationName() {
        return sameStationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withSameStationName(String sameStationName) {
        this.setSameStationName(sameStationName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.same_station_name
     *
     * @param sameStationName the value for t_plan_design_business_route.same_station_name
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setSameStationName(String sameStationName) {
        this.sameStationName = sameStationName == null ? null : sameStationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.is_same_route
     *
     * @return the value of t_plan_design_business_route.is_same_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Byte getIsSameRoute() {
        return isSameRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withIsSameRoute(Byte isSameRoute) {
        this.setIsSameRoute(isSameRoute);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.is_same_route
     *
     * @param isSameRoute the value for t_plan_design_business_route.is_same_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setIsSameRoute(Byte isSameRoute) {
        this.isSameRoute = isSameRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_business_route.create_time
     *
     * @return the value of t_plan_design_business_route.create_time
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public PlanDesignBusinessRoute withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_business_route.create_time
     *
     * @param createTime the value for t_plan_design_business_route.create_time
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", planDesignId=").append(planDesignId);
        sb.append(", planDesignResultId=").append(planDesignResultId);
        sb.append(", circleName=").append(circleName);
        sb.append(", businessType=").append(businessType);
        sb.append(", businessChannel=").append(businessChannel);
        sb.append(", stationA=").append(stationA);
        sb.append(", stationZ=").append(stationZ);
        sb.append(", businessCharacter=").append(businessCharacter);
        sb.append(", mainRoute=").append(mainRoute);
        sb.append(", backupRoute=").append(backupRoute);
        sb.append(", sameRouteDetail=").append(sameRouteDetail);
        sb.append(", sameStationName=").append(sameStationName);
        sb.append(", isSameRoute=").append(isSameRoute);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}