package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class PlanDesignCadDrawing implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.Id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.plan_design_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private Long planDesignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private Long planDesignResultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.cable_seg_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String cableSegName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.station_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String stationA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.station_type_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String stationTypeA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.station_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String stationZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.station_type_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String stationTypeZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.cable_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private String cableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_cad_drawing.create_time
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.Id
     *
     * @return the value of t_plan_design_cad_drawing.Id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.Id
     *
     * @param id the value for t_plan_design_cad_drawing.Id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.plan_design_id
     *
     * @return the value of t_plan_design_cad_drawing.plan_design_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Long getPlanDesignId() {
        return planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withPlanDesignId(Long planDesignId) {
        this.setPlanDesignId(planDesignId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.plan_design_id
     *
     * @param planDesignId the value for t_plan_design_cad_drawing.plan_design_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setPlanDesignId(Long planDesignId) {
        this.planDesignId = planDesignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.plan_design_result_id
     *
     * @return the value of t_plan_design_cad_drawing.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Long getPlanDesignResultId() {
        return planDesignResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withPlanDesignResultId(Long planDesignResultId) {
        this.setPlanDesignResultId(planDesignResultId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.plan_design_result_id
     *
     * @param planDesignResultId the value for t_plan_design_cad_drawing.plan_design_result_id
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setPlanDesignResultId(Long planDesignResultId) {
        this.planDesignResultId = planDesignResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.cable_seg_name
     *
     * @return the value of t_plan_design_cad_drawing.cable_seg_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getCableSegName() {
        return cableSegName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withCableSegName(String cableSegName) {
        this.setCableSegName(cableSegName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.cable_seg_name
     *
     * @param cableSegName the value for t_plan_design_cad_drawing.cable_seg_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setCableSegName(String cableSegName) {
        this.cableSegName = cableSegName == null ? null : cableSegName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.station_a
     *
     * @return the value of t_plan_design_cad_drawing.station_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getStationA() {
        return stationA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withStationA(String stationA) {
        this.setStationA(stationA);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.station_a
     *
     * @param stationA the value for t_plan_design_cad_drawing.station_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setStationA(String stationA) {
        this.stationA = stationA == null ? null : stationA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.station_type_a
     *
     * @return the value of t_plan_design_cad_drawing.station_type_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getStationTypeA() {
        return stationTypeA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withStationTypeA(String stationTypeA) {
        this.setStationTypeA(stationTypeA);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.station_type_a
     *
     * @param stationTypeA the value for t_plan_design_cad_drawing.station_type_a
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setStationTypeA(String stationTypeA) {
        this.stationTypeA = stationTypeA == null ? null : stationTypeA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.station_z
     *
     * @return the value of t_plan_design_cad_drawing.station_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getStationZ() {
        return stationZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withStationZ(String stationZ) {
        this.setStationZ(stationZ);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.station_z
     *
     * @param stationZ the value for t_plan_design_cad_drawing.station_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setStationZ(String stationZ) {
        this.stationZ = stationZ == null ? null : stationZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.station_type_z
     *
     * @return the value of t_plan_design_cad_drawing.station_type_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getStationTypeZ() {
        return stationTypeZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withStationTypeZ(String stationTypeZ) {
        this.setStationTypeZ(stationTypeZ);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.station_type_z
     *
     * @param stationTypeZ the value for t_plan_design_cad_drawing.station_type_z
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setStationTypeZ(String stationTypeZ) {
        this.stationTypeZ = stationTypeZ == null ? null : stationTypeZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.cable_name
     *
     * @return the value of t_plan_design_cad_drawing.cable_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public String getCableName() {
        return cableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withCableName(String cableName) {
        this.setCableName(cableName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.cable_name
     *
     * @param cableName the value for t_plan_design_cad_drawing.cable_name
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setCableName(String cableName) {
        this.cableName = cableName == null ? null : cableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_cad_drawing.create_time
     *
     * @return the value of t_plan_design_cad_drawing.create_time
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public PlanDesignCadDrawing withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_cad_drawing.create_time
     *
     * @param createTime the value for t_plan_design_cad_drawing.create_time
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_cad_drawing
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", planDesignId=").append(planDesignId);
        sb.append(", planDesignResultId=").append(planDesignResultId);
        sb.append(", cableSegName=").append(cableSegName);
        sb.append(", stationA=").append(stationA);
        sb.append(", stationTypeA=").append(stationTypeA);
        sb.append(", stationZ=").append(stationZ);
        sb.append(", stationTypeZ=").append(stationTypeZ);
        sb.append(", cableName=").append(cableName);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}