package cn.edu.guet.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlanDesignHistoryRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public PlanDesignHistoryRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNull() {
            addCriterion("plan_design_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIsNotNull() {
            addCriterion("plan_design_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdEqualTo(Long value) {
            addCriterion("plan_design_id =", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotEqualTo(Long value) {
            addCriterion("plan_design_id <>", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThan(Long value) {
            addCriterion("plan_design_id >", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_design_id >=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThan(Long value) {
            addCriterion("plan_design_id <", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_design_id <=", value, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdIn(List<Long> values) {
            addCriterion("plan_design_id in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotIn(List<Long> values) {
            addCriterion("plan_design_id not in", values, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdBetween(Long value1, Long value2) {
            addCriterion("plan_design_id between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andPlanDesignIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_design_id not between", value1, value2, "planDesignId");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoIsNull() {
            addCriterion("analyse_no is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoIsNotNull() {
            addCriterion("analyse_no is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoEqualTo(String value) {
            addCriterion("analyse_no =", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoNotEqualTo(String value) {
            addCriterion("analyse_no <>", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoGreaterThan(String value) {
            addCriterion("analyse_no >", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoGreaterThanOrEqualTo(String value) {
            addCriterion("analyse_no >=", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoLessThan(String value) {
            addCriterion("analyse_no <", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoLessThanOrEqualTo(String value) {
            addCriterion("analyse_no <=", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoLike(String value) {
            addCriterion("analyse_no like", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoNotLike(String value) {
            addCriterion("analyse_no not like", value, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoIn(List<String> values) {
            addCriterion("analyse_no in", values, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoNotIn(List<String> values) {
            addCriterion("analyse_no not in", values, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoBetween(String value1, String value2) {
            addCriterion("analyse_no between", value1, value2, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseNoNotBetween(String value1, String value2) {
            addCriterion("analyse_no not between", value1, value2, "analyseNo");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusIsNull() {
            addCriterion("analyse_status is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusIsNotNull() {
            addCriterion("analyse_status is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusEqualTo(Byte value) {
            addCriterion("analyse_status =", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusNotEqualTo(Byte value) {
            addCriterion("analyse_status <>", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusGreaterThan(Byte value) {
            addCriterion("analyse_status >", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("analyse_status >=", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusLessThan(Byte value) {
            addCriterion("analyse_status <", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusLessThanOrEqualTo(Byte value) {
            addCriterion("analyse_status <=", value, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusIn(List<Byte> values) {
            addCriterion("analyse_status in", values, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusNotIn(List<Byte> values) {
            addCriterion("analyse_status not in", values, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusBetween(Byte value1, Byte value2) {
            addCriterion("analyse_status between", value1, value2, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("analyse_status not between", value1, value2, "analyseStatus");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeIsNull() {
            addCriterion("analyse_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeIsNotNull() {
            addCriterion("analyse_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeEqualTo(Date value) {
            addCriterion("analyse_begin_time =", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeNotEqualTo(Date value) {
            addCriterion("analyse_begin_time <>", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeGreaterThan(Date value) {
            addCriterion("analyse_begin_time >", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("analyse_begin_time >=", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeLessThan(Date value) {
            addCriterion("analyse_begin_time <", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("analyse_begin_time <=", value, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeIn(List<Date> values) {
            addCriterion("analyse_begin_time in", values, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeNotIn(List<Date> values) {
            addCriterion("analyse_begin_time not in", values, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeBetween(Date value1, Date value2) {
            addCriterion("analyse_begin_time between", value1, value2, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("analyse_begin_time not between", value1, value2, "analyseBeginTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeIsNull() {
            addCriterion("analyse_end_time is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeIsNotNull() {
            addCriterion("analyse_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeEqualTo(Date value) {
            addCriterion("analyse_end_time =", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeNotEqualTo(Date value) {
            addCriterion("analyse_end_time <>", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeGreaterThan(Date value) {
            addCriterion("analyse_end_time >", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("analyse_end_time >=", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeLessThan(Date value) {
            addCriterion("analyse_end_time <", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("analyse_end_time <=", value, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeIn(List<Date> values) {
            addCriterion("analyse_end_time in", values, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeNotIn(List<Date> values) {
            addCriterion("analyse_end_time not in", values, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeBetween(Date value1, Date value2) {
            addCriterion("analyse_end_time between", value1, value2, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("analyse_end_time not between", value1, value2, "analyseEndTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIsNull() {
            addCriterion("analyse_time is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIsNotNull() {
            addCriterion("analyse_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeEqualTo(Integer value) {
            addCriterion("analyse_time =", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotEqualTo(Integer value) {
            addCriterion("analyse_time <>", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeGreaterThan(Integer value) {
            addCriterion("analyse_time >", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("analyse_time >=", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeLessThan(Integer value) {
            addCriterion("analyse_time <", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeLessThanOrEqualTo(Integer value) {
            addCriterion("analyse_time <=", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIn(List<Integer> values) {
            addCriterion("analyse_time in", values, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotIn(List<Integer> values) {
            addCriterion("analyse_time not in", values, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeBetween(Integer value1, Integer value2) {
            addCriterion("analyse_time between", value1, value2, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("analyse_time not between", value1, value2, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIsNull() {
            addCriterion("system_cad_file_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIsNotNull() {
            addCriterion("system_cad_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdEqualTo(Integer value) {
            addCriterion("system_cad_file_id =", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotEqualTo(Integer value) {
            addCriterion("system_cad_file_id <>", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdGreaterThan(Integer value) {
            addCriterion("system_cad_file_id >", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_cad_file_id >=", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdLessThan(Integer value) {
            addCriterion("system_cad_file_id <", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_cad_file_id <=", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIn(List<Integer> values) {
            addCriterion("system_cad_file_id in", values, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotIn(List<Integer> values) {
            addCriterion("system_cad_file_id not in", values, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdBetween(Integer value1, Integer value2) {
            addCriterion("system_cad_file_id between", value1, value2, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_cad_file_id not between", value1, value2, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIsNull() {
            addCriterion("system_cad_file_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIsNotNull() {
            addCriterion("system_cad_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameEqualTo(String value) {
            addCriterion("system_cad_file_name =", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotEqualTo(String value) {
            addCriterion("system_cad_file_name <>", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameGreaterThan(String value) {
            addCriterion("system_cad_file_name >", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_cad_file_name >=", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLessThan(String value) {
            addCriterion("system_cad_file_name <", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLessThanOrEqualTo(String value) {
            addCriterion("system_cad_file_name <=", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLike(String value) {
            addCriterion("system_cad_file_name like", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotLike(String value) {
            addCriterion("system_cad_file_name not like", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIn(List<String> values) {
            addCriterion("system_cad_file_name in", values, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotIn(List<String> values) {
            addCriterion("system_cad_file_name not in", values, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameBetween(String value1, String value2) {
            addCriterion("system_cad_file_name between", value1, value2, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotBetween(String value1, String value2) {
            addCriterion("system_cad_file_name not between", value1, value2, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIsNull() {
            addCriterion("system_cad_file_url is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIsNotNull() {
            addCriterion("system_cad_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlEqualTo(String value) {
            addCriterion("system_cad_file_url =", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotEqualTo(String value) {
            addCriterion("system_cad_file_url <>", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlGreaterThan(String value) {
            addCriterion("system_cad_file_url >", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("system_cad_file_url >=", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLessThan(String value) {
            addCriterion("system_cad_file_url <", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLessThanOrEqualTo(String value) {
            addCriterion("system_cad_file_url <=", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLike(String value) {
            addCriterion("system_cad_file_url like", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotLike(String value) {
            addCriterion("system_cad_file_url not like", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIn(List<String> values) {
            addCriterion("system_cad_file_url in", values, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotIn(List<String> values) {
            addCriterion("system_cad_file_url not in", values, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlBetween(String value1, String value2) {
            addCriterion("system_cad_file_url between", value1, value2, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotBetween(String value1, String value2) {
            addCriterion("system_cad_file_url not between", value1, value2, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIsNull() {
            addCriterion("system_excel_file_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIsNotNull() {
            addCriterion("system_excel_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdEqualTo(Integer value) {
            addCriterion("system_excel_file_id =", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotEqualTo(Integer value) {
            addCriterion("system_excel_file_id <>", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdGreaterThan(Integer value) {
            addCriterion("system_excel_file_id >", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_excel_file_id >=", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdLessThan(Integer value) {
            addCriterion("system_excel_file_id <", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_excel_file_id <=", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIn(List<Integer> values) {
            addCriterion("system_excel_file_id in", values, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotIn(List<Integer> values) {
            addCriterion("system_excel_file_id not in", values, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdBetween(Integer value1, Integer value2) {
            addCriterion("system_excel_file_id between", value1, value2, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_excel_file_id not between", value1, value2, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIsNull() {
            addCriterion("system_excel_file_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIsNotNull() {
            addCriterion("system_excel_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameEqualTo(String value) {
            addCriterion("system_excel_file_name =", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotEqualTo(String value) {
            addCriterion("system_excel_file_name <>", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameGreaterThan(String value) {
            addCriterion("system_excel_file_name >", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_excel_file_name >=", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLessThan(String value) {
            addCriterion("system_excel_file_name <", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLessThanOrEqualTo(String value) {
            addCriterion("system_excel_file_name <=", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLike(String value) {
            addCriterion("system_excel_file_name like", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotLike(String value) {
            addCriterion("system_excel_file_name not like", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIn(List<String> values) {
            addCriterion("system_excel_file_name in", values, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotIn(List<String> values) {
            addCriterion("system_excel_file_name not in", values, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameBetween(String value1, String value2) {
            addCriterion("system_excel_file_name between", value1, value2, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotBetween(String value1, String value2) {
            addCriterion("system_excel_file_name not between", value1, value2, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIsNull() {
            addCriterion("system_excel_file_url is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIsNotNull() {
            addCriterion("system_excel_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlEqualTo(String value) {
            addCriterion("system_excel_file_url =", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotEqualTo(String value) {
            addCriterion("system_excel_file_url <>", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlGreaterThan(String value) {
            addCriterion("system_excel_file_url >", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("system_excel_file_url >=", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLessThan(String value) {
            addCriterion("system_excel_file_url <", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLessThanOrEqualTo(String value) {
            addCriterion("system_excel_file_url <=", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLike(String value) {
            addCriterion("system_excel_file_url like", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotLike(String value) {
            addCriterion("system_excel_file_url not like", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIn(List<String> values) {
            addCriterion("system_excel_file_url in", values, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotIn(List<String> values) {
            addCriterion("system_excel_file_url not in", values, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlBetween(String value1, String value2) {
            addCriterion("system_excel_file_url between", value1, value2, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotBetween(String value1, String value2) {
            addCriterion("system_excel_file_url not between", value1, value2, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIsNull() {
            addCriterion("channel_excel_file_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIsNotNull() {
            addCriterion("channel_excel_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdEqualTo(Integer value) {
            addCriterion("channel_excel_file_id =", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotEqualTo(Integer value) {
            addCriterion("channel_excel_file_id <>", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdGreaterThan(Integer value) {
            addCriterion("channel_excel_file_id >", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_excel_file_id >=", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdLessThan(Integer value) {
            addCriterion("channel_excel_file_id <", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_excel_file_id <=", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIn(List<Integer> values) {
            addCriterion("channel_excel_file_id in", values, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotIn(List<Integer> values) {
            addCriterion("channel_excel_file_id not in", values, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_excel_file_id between", value1, value2, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_excel_file_id not between", value1, value2, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIsNull() {
            addCriterion("channel_excel_file_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIsNotNull() {
            addCriterion("channel_excel_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameEqualTo(String value) {
            addCriterion("channel_excel_file_name =", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotEqualTo(String value) {
            addCriterion("channel_excel_file_name <>", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameGreaterThan(String value) {
            addCriterion("channel_excel_file_name >", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_name >=", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLessThan(String value) {
            addCriterion("channel_excel_file_name <", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLessThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_name <=", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLike(String value) {
            addCriterion("channel_excel_file_name like", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotLike(String value) {
            addCriterion("channel_excel_file_name not like", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIn(List<String> values) {
            addCriterion("channel_excel_file_name in", values, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotIn(List<String> values) {
            addCriterion("channel_excel_file_name not in", values, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameBetween(String value1, String value2) {
            addCriterion("channel_excel_file_name between", value1, value2, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotBetween(String value1, String value2) {
            addCriterion("channel_excel_file_name not between", value1, value2, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIsNull() {
            addCriterion("channel_excel_file_url is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIsNotNull() {
            addCriterion("channel_excel_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlEqualTo(String value) {
            addCriterion("channel_excel_file_url =", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotEqualTo(String value) {
            addCriterion("channel_excel_file_url <>", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlGreaterThan(String value) {
            addCriterion("channel_excel_file_url >", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_url >=", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLessThan(String value) {
            addCriterion("channel_excel_file_url <", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLessThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_url <=", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLike(String value) {
            addCriterion("channel_excel_file_url like", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotLike(String value) {
            addCriterion("channel_excel_file_url not like", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIn(List<String> values) {
            addCriterion("channel_excel_file_url in", values, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotIn(List<String> values) {
            addCriterion("channel_excel_file_url not in", values, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlBetween(String value1, String value2) {
            addCriterion("channel_excel_file_url between", value1, value2, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotBetween(String value1, String value2) {
            addCriterion("channel_excel_file_url not between", value1, value2, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogIsNull() {
            addCriterion("analyse_log is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogIsNotNull() {
            addCriterion("analyse_log is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogEqualTo(String value) {
            addCriterion("analyse_log =", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogNotEqualTo(String value) {
            addCriterion("analyse_log <>", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogGreaterThan(String value) {
            addCriterion("analyse_log >", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogGreaterThanOrEqualTo(String value) {
            addCriterion("analyse_log >=", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogLessThan(String value) {
            addCriterion("analyse_log <", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogLessThanOrEqualTo(String value) {
            addCriterion("analyse_log <=", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogLike(String value) {
            addCriterion("analyse_log like", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogNotLike(String value) {
            addCriterion("analyse_log not like", value, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogIn(List<String> values) {
            addCriterion("analyse_log in", values, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogNotIn(List<String> values) {
            addCriterion("analyse_log not in", values, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogBetween(String value1, String value2) {
            addCriterion("analyse_log between", value1, value2, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseLogNotBetween(String value1, String value2) {
            addCriterion("analyse_log not between", value1, value2, "analyseLog");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdIsNull() {
            addCriterion("analyse_staff_id is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdIsNotNull() {
            addCriterion("analyse_staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdEqualTo(Long value) {
            addCriterion("analyse_staff_id =", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdNotEqualTo(Long value) {
            addCriterion("analyse_staff_id <>", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdGreaterThan(Long value) {
            addCriterion("analyse_staff_id >", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("analyse_staff_id >=", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdLessThan(Long value) {
            addCriterion("analyse_staff_id <", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("analyse_staff_id <=", value, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdIn(List<Long> values) {
            addCriterion("analyse_staff_id in", values, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdNotIn(List<Long> values) {
            addCriterion("analyse_staff_id not in", values, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdBetween(Long value1, Long value2) {
            addCriterion("analyse_staff_id between", value1, value2, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("analyse_staff_id not between", value1, value2, "analyseStaffId");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameIsNull() {
            addCriterion("analyse_staff_name is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameIsNotNull() {
            addCriterion("analyse_staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameEqualTo(String value) {
            addCriterion("analyse_staff_name =", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameNotEqualTo(String value) {
            addCriterion("analyse_staff_name <>", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameGreaterThan(String value) {
            addCriterion("analyse_staff_name >", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("analyse_staff_name >=", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameLessThan(String value) {
            addCriterion("analyse_staff_name <", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameLessThanOrEqualTo(String value) {
            addCriterion("analyse_staff_name <=", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameLike(String value) {
            addCriterion("analyse_staff_name like", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameNotLike(String value) {
            addCriterion("analyse_staff_name not like", value, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameIn(List<String> values) {
            addCriterion("analyse_staff_name in", values, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameNotIn(List<String> values) {
            addCriterion("analyse_staff_name not in", values, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameBetween(String value1, String value2) {
            addCriterion("analyse_staff_name between", value1, value2, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andAnalyseStaffNameNotBetween(String value1, String value2) {
            addCriterion("analyse_staff_name not between", value1, value2, "analyseStaffName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 21 19:52:21 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}