package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignPhysicsRoute;
import cn.edu.guet.bean.PlanDesignPhysicsRouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignPhysicsRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    long countByExample(PlanDesignPhysicsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int deleteByExample(PlanDesignPhysicsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int insert(PlanDesignPhysicsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int insertSelective(PlanDesignPhysicsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    List<PlanDesignPhysicsRoute> selectByExampleWithRowbounds(PlanDesignPhysicsRouteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    List<PlanDesignPhysicsRoute> selectByExample(PlanDesignPhysicsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    PlanDesignPhysicsRoute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignPhysicsRoute record, @Param("example") PlanDesignPhysicsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignPhysicsRoute record, @Param("example") PlanDesignPhysicsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignPhysicsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_physics_route
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByPrimaryKey(PlanDesignPhysicsRoute record);
}