package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignHistoryRecord;
import cn.edu.guet.bean.PlanDesignHistoryRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignHistoryRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    long countByExample(PlanDesignHistoryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int deleteByExample(PlanDesignHistoryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int insert(PlanDesignHistoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int insertSelective(PlanDesignHistoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    List<PlanDesignHistoryRecord> selectByExampleWithRowbounds(PlanDesignHistoryRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    List<PlanDesignHistoryRecord> selectByExample(PlanDesignHistoryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    PlanDesignHistoryRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignHistoryRecord record, @Param("example") PlanDesignHistoryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignHistoryRecord record, @Param("example") PlanDesignHistoryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignHistoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_history_record
     *
     * @mbg.generated Wed Jun 21 19:52:21 CST 2023
     */
    int updateByPrimaryKey(PlanDesignHistoryRecord record);
}