package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignRouteCable;
import cn.edu.guet.bean.PlanDesignRouteCableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignRouteCableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    long countByExample(PlanDesignRouteCableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int deleteByExample(PlanDesignRouteCableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int insert(PlanDesignRouteCable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int insertSelective(PlanDesignRouteCable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    List<PlanDesignRouteCable> selectByExampleWithRowbounds(PlanDesignRouteCableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    List<PlanDesignRouteCable> selectByExample(PlanDesignRouteCableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    PlanDesignRouteCable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignRouteCable record, @Param("example") PlanDesignRouteCableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignRouteCable record, @Param("example") PlanDesignRouteCableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignRouteCable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_route_cable
     *
     * @mbg.generated Tue Jun 20 20:39:50 CST 2023
     */
    int updateByPrimaryKey(PlanDesignRouteCable record);
}