package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignExcelRecord;
import cn.edu.guet.bean.PlanDesignExcelRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignExcelRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    long countByExample(PlanDesignExcelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int deleteByExample(PlanDesignExcelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int insert(PlanDesignExcelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int insertSelective(PlanDesignExcelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    List<PlanDesignExcelRecord> selectByExampleWithRowbounds(PlanDesignExcelRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    List<PlanDesignExcelRecord> selectByExample(PlanDesignExcelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    PlanDesignExcelRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignExcelRecord record, @Param("example") PlanDesignExcelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignExcelRecord record, @Param("example") PlanDesignExcelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignExcelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_excel_record
     *
     * @mbg.generated Tue Jun 20 21:02:33 CST 2023
     */
    int updateByPrimaryKey(PlanDesignExcelRecord record);
}