package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignBusinessRoute;
import cn.edu.guet.bean.PlanDesignBusinessRouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignBusinessRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    long countByExample(PlanDesignBusinessRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int deleteByExample(PlanDesignBusinessRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int insert(PlanDesignBusinessRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int insertSelective(PlanDesignBusinessRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    List<PlanDesignBusinessRoute> selectByExampleWithRowbounds(PlanDesignBusinessRouteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    List<PlanDesignBusinessRoute> selectByExample(PlanDesignBusinessRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    PlanDesignBusinessRoute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignBusinessRoute record, @Param("example") PlanDesignBusinessRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignBusinessRoute record, @Param("example") PlanDesignBusinessRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignBusinessRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_business_route
     *
     * @mbg.generated Tue Jun 20 20:11:55 CST 2023
     */
    int updateByPrimaryKey(PlanDesignBusinessRoute record);
}